name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.base_ref != 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3.1.0

      - name: Install npm
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20.14.0

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run test
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
