name: CI

on:
  push:
    branches:
      - "*"

env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.base_ref != 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4.1.7

      - name: Install npm
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.15.1

      - name: Install npm dependencies
        run: npm ci

      - name: Create env file
        run: |
          cat .env.example > .env
          sed -i -e "s/__NODE_ENV__/testing/g" ./.env
          sed -i -e "s/__APP_NAME__/eso-status/g" ./.env
          sed -i -e "s/__APP_PROTOCOL__/https/g" ./.env
          sed -i -e "s/__APP_HOST__/api.eso-status.local/g" ./.env
          sed -i -e "s/__APP_PORT__/443/g" ./.env
          sed -i -e "s/__SSL_PRIVATE__/-----BEGIN PRIVATE KEY----- MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCJ7vt9Xpo6r0I 2SSwXkXfd6F20dQwFqLD8jzqtjWduP5aRhi2VBuTBUJqM29ZbAp07UVKi167Ksyh V+8kfR9/BflbMBpVGYu9phjscuwd7E+dyVqUd3eWPUcMW7if25sO+QWkjk7e7pi6 UQNicpLV1aIfv5jjkGbo8CQkx9vNnZRBx6Yc/bfcRmb42ZM6WZdg/kgmZguZ1y6o 0xW8pn8s+qAwi2qFm5bO2ZZjnOUie8ijCjeTSkJoyMfqLBsASmRRfT0XlknFNLMb SDTVElPGfsAGvYqMKyQoephONOP/fD5JBQIxDL2dKG25L8fCKOP+w8JLqzWlvLhU +tbjtnArAgMBAAECggEBALKPen3p4s90+6+UjPKLcTWJP30Yk046sy0ErtOqCftp dLuvdfDRv55iGuezMDgMbj2FLdHWBaSbQyErzys+y+W1p9QelEkpumQLyyZCtzb5 62sREPY0PU52Qs5x2IVkoeGOUos5uf27b8kC0tsKxlJVLMqIGmNHne2jVYpiKJub MtprzKJ0wpCorstnlrKkggd28GL8DYahJN1F68GRNjA5ryTqeiQrRYZrcUc4ErzP fRKE3OVi8vtiZ2QIdovkYoEqQIa+YtylrFo3oXZexbZRVGU/P/0hi3qrR7PtMKaZ d3+SzewLu0vMhO4kVSbamnnqLBT3A0U4oyn9Z+I0GhECgYEA7/zvk/1vqfyoao3v x4b1zGM2NkDTHJajhQppjm3muTr6kvU53fORa6H9yZ+ux+25cpnRD24jSXnmDaQ1 mt+pttm4Ic99a/ZeHKcfXMqGl2Wax8wvuOJSGFkMF/581qBK/Wr75a2RszOUvOV5 3Q2cRUoitLo4aDKQ3qOkJVVcENMCgYEAzxv16ZGNRt78yxFBJ5LxiV66K0Mg1uJ8 ZoNmaS7zDFSU32nAiUAkBxutoNhUIH1iKf22l38iAF5rUIisGOyON4vss5u5MUfj sev5Dd86/29kCE6EmwLlNCRiPNDm/LXeDUMPwreJmnVvr+pOK4XtYagGRXrFgGOu fzequThNTEkCgYEAkXbTEPTRNkv7GXsnF93qJxULyx7H19BHFWEWUkqzSxtAvsr9 ZFc6ke8Cka/ElVK20YwCeEPeB69njmU2SMXBbR/SyEuoTkRrDxsNm4T2x9XCV9Cg LISiFjgDaJfMu5s1WR37yV/HrMNbKJQ/pYmWazlgiANIJYBg51JxMF/pChkCgYBw nc+V9eNQSihDc1puXmSgQbYRmCrfLcBfLcweHb1jUwqwgRyEhTAR/WboMzlrgUJD ewYyUpr2gGDyJZ8O3nJmmdtXvrFwrpqNQLboaB34j2VhbvCEKYrgU3hngWBYwbvA klqbkplsN7dHfKyM1gJCO89NMHj8WzejTW2z0X2WoQKBgFqiXgxRqk9NZX2p0noW fPa4uB6fy1CrrzEI1v8eoVVNOcJDUTpJSytW4396sZDwyb+PxNRtKyUpVyGcBw+e MzgyO33M2yW/zEj3eXJyiXSdFf3FKWEM8HUCPwyiJxi38pycCbn+SodA9jdMSrbK TccVREQq5BCcZm7Ke2I+78zH -----END PRIVATE KEY-----/g" ./.env
          sed -i -e "s/__SSL_CERTIFICATE__/-----BEGIN CERTIFICATE----- MIIEQzCCAqugAwIBAgIRAKocQnWy6o53LxzArcYAUKAwDQYJKoZIhvcNAQELBQAw aTEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMR8wHQYDVQQLDBZkb3Yx MThAZG92MTE4cy1NQlAubGFuMSYwJAYDVQQDDB1ta2NlcnQgZG92MTE4QGRvdjEx OHMtTUJQLmxhbjAeFw0yNDA3MjQxMTQ5MzNaFw0yNjEwMjQxMTQ5MzNaMFQxJzAl BgNVBAoTHm1rY2VydCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTEpMCcGA1UECwwg ZG92MTE4QGRvdjExOHMtTWFjQm9vay1Qcm8ubG9jYWwwggEiMA0GCSqGSIb3DQEB AQUAA4IBDwAwggEKAoIBAQDCJ7vt9Xpo6r0I2SSwXkXfd6F20dQwFqLD8jzqtjWd uP5aRhi2VBuTBUJqM29ZbAp07UVKi167KsyhV+8kfR9/BflbMBpVGYu9phjscuwd 7E+dyVqUd3eWPUcMW7if25sO+QWkjk7e7pi6UQNicpLV1aIfv5jjkGbo8CQkx9vN nZRBx6Yc/bfcRmb42ZM6WZdg/kgmZguZ1y6o0xW8pn8s+qAwi2qFm5bO2ZZjnOUi e8ijCjeTSkJoyMfqLBsASmRRfT0XlknFNLMbSDTVElPGfsAGvYqMKyQoephONOP/ fD5JBQIxDL2dKG25L8fCKOP+w8JLqzWlvLhU+tbjtnArAgMBAAGjezB5MA4GA1Ud DwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAfBgNVHSMEGDAWgBQXJu0d 2mJoi0Iu0a8UUiQRK13KljAxBgNVHREEKjAoghRhcGkuZXNvLXN0YXR1cy5sb2Nh bIcQAAAAAAAAAAAAAAAAAAAAATANBgkqhkiG9w0BAQsFAAOCAYEAFgfA97V1mgrP zWQbiXOQq2T0IhS1oRfWxaks+9VT3eDH4vf8GL2B8Tc/18S8YFFWQx8pRQ2kbC30 jXMkSuy4njT8Wbr+qQ8HNmuJ/vPL2+AVBNmF35mVOyF5qPrnAd3MjO7b3ozLCWP6 VKuQNM3jGcgfvT8EjP2COH/HvH5fYiWH55Eex/KqI94v8ahvz6Jx+lDXCOt5mSY3 jnuf0EU9RfIeNjaboQprOTig+ieOvE5Mc723NANmz0eH/kjD6s+F6FObpZUTgJQA mL7ba94EyNkannhfxPWsNY7TfCKkjSjUCydolZVQ2LAL2hnBwq9v41Ub/+8glbkB yvv6WAm0qHfThch3Nf/y63vZ+aXFg+7ZtSEEl+qgBq4W8f8eO7Ll2oZwxNSDMjpW 8lfTG5fRqHMxyNOhZlzPp3f9SRslS3HN3pc+YVag9IwPkAuVdpBFCijwnFZXijZO 4Kxpw3RDM0aA5Pr4IR4HrhZ8R1A3eXcKItzHot3Gfeii1lwzNMaX -----END CERTIFICATE-----/g" ./.env
          sed -i -e "s/__SSL_CA_BUNDLE__/-----BEGIN CERTIFICATE----- MIIEQzCCAqugAwIBAgIRAKocQnWy6o53LxzArcYAUKAwDQYJKoZIhvcNAQELBQAw aTEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMR8wHQYDVQQLDBZkb3Yx MThAZG92MTE4cy1NQlAubGFuMSYwJAYDVQQDDB1ta2NlcnQgZG92MTE4QGRvdjEx OHMtTUJQLmxhbjAeFw0yNDA3MjQxMTQ5MzNaFw0yNjEwMjQxMTQ5MzNaMFQxJzAl BgNVBAoTHm1rY2VydCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTEpMCcGA1UECwwg ZG92MTE4QGRvdjExOHMtTWFjQm9vay1Qcm8ubG9jYWwwggEiMA0GCSqGSIb3DQEB AQUAA4IBDwAwggEKAoIBAQDCJ7vt9Xpo6r0I2SSwXkXfd6F20dQwFqLD8jzqtjWd uP5aRhi2VBuTBUJqM29ZbAp07UVKi167KsyhV+8kfR9/BflbMBpVGYu9phjscuwd 7E+dyVqUd3eWPUcMW7if25sO+QWkjk7e7pi6UQNicpLV1aIfv5jjkGbo8CQkx9vN nZRBx6Yc/bfcRmb42ZM6WZdg/kgmZguZ1y6o0xW8pn8s+qAwi2qFm5bO2ZZjnOUi e8ijCjeTSkJoyMfqLBsASmRRfT0XlknFNLMbSDTVElPGfsAGvYqMKyQoephONOP/ fD5JBQIxDL2dKG25L8fCKOP+w8JLqzWlvLhU+tbjtnArAgMBAAGjezB5MA4GA1Ud DwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAfBgNVHSMEGDAWgBQXJu0d 2mJoi0Iu0a8UUiQRK13KljAxBgNVHREEKjAoghRhcGkuZXNvLXN0YXR1cy5sb2Nh bIcQAAAAAAAAAAAAAAAAAAAAATANBgkqhkiG9w0BAQsFAAOCAYEAFgfA97V1mgrP zWQbiXOQq2T0IhS1oRfWxaks+9VT3eDH4vf8GL2B8Tc/18S8YFFWQx8pRQ2kbC30 jXMkSuy4njT8Wbr+qQ8HNmuJ/vPL2+AVBNmF35mVOyF5qPrnAd3MjO7b3ozLCWP6 VKuQNM3jGcgfvT8EjP2COH/HvH5fYiWH55Eex/KqI94v8ahvz6Jx+lDXCOt5mSY3 jnuf0EU9RfIeNjaboQprOTig+ieOvE5Mc723NANmz0eH/kjD6s+F6FObpZUTgJQA mL7ba94EyNkannhfxPWsNY7TfCKkjSjUCydolZVQ2LAL2hnBwq9v41Ub/+8glbkB yvv6WAm0qHfThch3Nf/y63vZ+aXFg+7ZtSEEl+qgBq4W8f8eO7Ll2oZwxNSDMjpW 8lfTG5fRqHMxyNOhZlzPp3f9SRslS3HN3pc+YVag9IwPkAuVdpBFCijwnFZXijZO 4Kxpw3RDM0aA5Pr4IR4HrhZ8R1A3eXcKItzHot3Gfeii1lwzNMaX -----END CERTIFICATE-----/g" ./.env
          sed -i -e "s/__DB_TYPE__/sqlite/g" ./.env
          sed -i -e "s/__DB_HOST__//g" ./.env
          sed -i -e "s/__DB_PORT__//g" ./.env
          sed -i -e "s#__DB_NAME__#src/database/dev#g" ./.env
          sed -i -e "s/__DB_USER__//g" ./.env
          sed -i -e "s/__DB_PASSWORD__//g" ./.env
          sed -i -e "s/__DB_DEBUG__/$DB_DEBUG/g" ./.env
          sed -i -e "s/__FORUM_MESSAGE_UPDATE_INTERVAL__/1000/g" ./.env
          sed -i -e "s/__LIVE_SERVICES_UPDATE_INTERVAL__/1000/g" ./.env
          sed -i -e "s/__SERVICE_ALERTS_UPDATE_INTERVAL__/1000/g" ./.env
          sed -i -e "s/__QUEUE_INTERVAL__/1000/g" ./.env
          sed -i -e "s/__AWS_ACCESS_KEY_ID__/$AWS_ACCESS_KEY_ID/g" ./.env
          sed -i -e "s/__AWS_SECRET_ACCESS_KEY__/$AWS_SECRET_ACCESS_KEY/g" ./.env
          sed -i -e "s/__AWS_REGION__/$AWS_REGION/g" ./.env
          sed -i -e "s/__CLOUDWATCH_GROUP_NAME__/$CLOUDWATCH_GROUP_NAME/g" ./.env
          sed -i -e "s/__CLOUDWATCH_STREAM_NAME__/$CLOUDWATCH_STREAM_NAME/g" ./.env

      - name: Build assets
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run database migration
        run: npm run migration:run

      - name: Run seeders
        run: npm run seed

      - name: Run test
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
