name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.base_ref != 'refs/heads/main'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4.1.7

      - name: Install npm
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.15.1

      - name: Install npm dependencies
        run: npm ci

      - name: Create env file
        run: |
          cp .env.example .env.test
          sed -i -e "s/APP_ENV=development/APP_ENV=testing/g" .env.test
          cp .env.test .env

      - name: Build assets
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run database migration
        run: npm run migration:run

      - name: Run seeders
        run: npm run seed

      - name: Run test
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
